name: glances-pro
version: '20.04'
summary: PyQt5 runtime stack based on core20.
description: This snap is to be consumed by various PyQt5 apps which uses Qt 5.9+ Qt provides C++ classes and QML types for rendering GUI.
grade: stable
confinement: strict
base: core20

architectures:
  - build-on: amd64
    run-on: amd64

slots:
  glances-pro:
    interface: content
    read:
      - /

parts:
  python-ppa:
    plugin: nil
    override-pull: |
      snapcraftctl pull
      apt install software-properties-common -y
      add-apt-repository ppa:deadsnakes/ppa -y
      apt update

  deps:
    plugin: nil
    after: [ python-ppa ]
    stage-packages:
      - mpv # this is ppa version of mpv
      - ffmpeg # used by y2mate for merging audio video
      - adwaita-icon-theme
      - dmz-cursor-theme
      - gnome-themes-standard
      - gsettings-desktop-schemas
      - libdb5.3
      - libgdk-pixbuf2.0-0
      - libglib2.0-0
      - libglu1-mesa
      - libslang2
      - libxkbcommon0
      - light-themes
      - locales-all
      - python3-pyqt5
      - qt5-gtk-platformtheme
      - shared-mime-info
      - ttf-ubuntu-font-family
      - xdg-user-dirs
      - samba-libs
      - build-essential
      - libssl-dev
      - libffi-dev


  glances-pro:
    plugin: python
    source: .
    python-packages:
      - requests
      - cryptography
      - psutil
      - python-slugify
      - yt-dlp
    build-packages:
      - python3.8-dev
    build-attributes: [ keep-execstack ]
